# Site settings
title: Liping Zhang's Home Page
name: Liping Zhang's Blog # your name
email: zlpmichelle@gmail.com # your email address
description: >
    Liping Zhang's Blog using A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://zlpmichelle.github.io" # the base hostname & protocol for your site
twitter_username: zlpmichelle # your Twitter username
github_username: zlpmichelle # your Github username
# disqus_username: zlpmichelle # your disqus username

# google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
